Feature/user profile screen
domingues-dev/newhome pull request #2
Opened 2021-04-07 17:30 UTC by domingues-dev

User profile screen basic view layout and configuration.
PS: I had 2 smaller commits and i thought that if i would push them at the same time i would still have 2 commits on git, but it seems it was not the case. I will commit and push smaller chunks of code from now on.

You can focus on the user profile view controller and viper architecture.

2021-04-08 10:18 UTC, MarcoSDomingues requested changes

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Common/Base View Controllers/BaseNavigationController.swift
> +            .foregroundColor: UIColor(named: "dark-blue") ?? UIColor.black
Nice idea to put and use the colors from the assets.. but it would also be nice to have a file with shorthands to access the colors in a single location, because in the future if we want to change the color asset name, we just need to change in a single file instead of searching all over the source code.

Something like this would be nice:
```
enum AppColors {
    static var white: UIColor { UIColor.white }
    static var black: UIColor { UIColor.black }
    static var darkBlue: UIColor { UIColor(named: "dark-blue") }
    ...
}
```

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/Saved/ViewControllers/SavedViewController.swift
> +class SavedViewController: UIViewController {
This naming doesn't seem very good.. Maybe "FavoriteItems" or "LikedItems" would be better?

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/Presenters/ProfilePresenter.swift
> +        view.updateTitle("Profile")
This hardcoded string should be in a .strings file to facilitate localisations in the future, and to have unique point of access

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +    lazy var cameraButton: UIButton = {
The button looks good, but if you see, you are basically replicating code for the camera and settings button.

You should create a subclass of UIButton for this type of buttons to facilitate the reuse of the button across the application

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +    lazy var purchasesButton: UIButton = {
Same thing for these buttons. They look very good, but you should create a subclass of UIButton for this type of buttons to facilitate the reuse of the button across the application

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +    lazy var signoutButton: UIButton = {
The sign out button should be a standalone view as well. And the signout label should be part of the button as well because if I click on the label to sign out, I expect the app to respond to the click, and not only if I click on the image.

For this view, subclass a UIControl instead of an UIButton

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +        view.backgroundColor = .white
Should use AppColors.white instead of directly .white

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +        navigationItem.rightBarButtonItem?.tintColor = UIColor(named: "dark-blue")
navigation bar button items should use the tint color of the navigation bar.. you should define tint on the navigation bar instead of the tint in the button

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +            NSLayoutConstraint.activate([
identantion is wrong

2021-04-08 10:18 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +}
This screen looks very good in terms of UI, but if you run in a smaller device, it will not look very good.. 
The views should be inside a Scroll view to fit in all devices.

Also, I would like to see the use of a collection view, because we may want to add new sections in the future, and that would be easier if we were using one.

Imagine we want to add new action buttons, we could just add the needed cells instead of having to add new views and fit them with constraints where we wanted them to be

2021-04-08 14:47 UTC, domingues-dev commented on newhome/newhome/Common/Base View Controllers/BaseNavigationController.swift
> +            .foregroundColor: UIColor(named: "dark-blue") ?? UIColor.black
Done.
Did the same for the icons.

2021-04-08 14:50 UTC, domingues-dev commented on newhome/newhome/Scenes/Saved/ViewControllers/SavedViewController.swift
> +class SavedViewController: UIViewController {
Done.
Changed it  to "FavoriteItems".

2021-04-13 17:49 UTC, MarcoSDomingues requested changes

2021-04-13 17:49 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/Views/ButtonCollectionViewCell.swift
> +        if button.isSelected {
I know this is only for testing purposes, but you can override this property in the `ProfileButtonView` class.

Something like this:

```
override var isSelected: Bool {
  didSet {
     if isSelected {
         ...
     } else {
          ...
     }
  }
}
```

2021-04-13 17:49 UTC, MarcoSDomingues commented on newhome/newhome/Scenes/User Profile/ViewControllers/ProfileViewController.swift
> +        let buttonCell = ButtonCollectionViewCell.dequeue(from: collectionView, for: indexPath)
This is not good idea. Every time the collection view is dequeuing a cell, you are basically dequeuing and creating instances for every cell type, when in reality you should only be dequeuing and instantiating a single cell.

You should only dequeue the cells inside each switch case

2021-04-15 07:52 UTC, merged